{
 "title": "CloudWatch(SecurityHub) Dashboard",
 "tags": [
  "CloudWatch",
  "SecurityHub"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Resource Type",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "stats count(*) as resource by  detail.findings.0.Resources.0.Type AS resourceType ",
     "logGroups": [
      {
       "accountId": "159088646233",
       "arn": "arn:aws:logs:ap-northeast-2:159088646233:log-group:/aws/events/Securityhub:*",
       "name": "/aws/events/Securityhub"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average",
     "statsGroups": [ "resourceType" ]
    }
   ]
  },
  {
   "title": "Service Detection Count",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expression": "stats count(*) as SERVICE_COUNT by detail.findings.0.ProductName AS SERVICE ",
     "logGroups": [
      {
       "accountId": "159088646233",
       "arn": "arn:aws:logs:ap-northeast-2:159088646233:log-group:/aws/events/Securityhub:*",
       "name": "/aws/events/Securityhub"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average",
     "statsGroups": [ "SERVICE" ]
    }
   ]
  },
  {
   "title": "compliance count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "stats count(*) as complianceStautsCount by detail.findings.0.Compliance.Status as complianceStatus | sort complianceStautsCount desc",
     "logGroups": [
      {
       "accountId": "159088646233",
       "arn": "arn:aws:logs:ap-northeast-2:159088646233:log-group:/aws/events/Securityhub:*",
       "name": "/aws/events/Securityhub"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average",
     "statsGroups": [ "complianceStatus" ]
    }
   ]
  },
  {
   "title": "Serverity Label Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "stats count(*) as SEVERITY_COUNT by  detail.findings.0.FindingProviderFields.Severity.Label AS SEVERITY \n",
     "logGroups": [
      {
       "accountId": "159088646233",
       "arn": "arn:aws:logs:ap-northeast-2:159088646233:log-group:/aws/events/Securityhub:*",
       "name": "/aws/events/Securityhub"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average",
     "statsGroups": [ "SEVERITY" ]
    }
   ]
  }
 ]
}